// Loads contract ABI (from src/abi/, generated by `npm run copy-abi`) and the
// deployed address (from env). useContract() turns these into ethers.Contract.
// Addresses live in frontend/.env.local as NEXT_PUBLIC_<NAME>_ADDRESS.

import type { ContractName } from "./constants";

import KeyCoinABI from "@/abi/KeyCoin.json";
import GameTokenABI from "@/abi/GameToken.json";
import GameStoreABI from "@/abi/GameStore.json";
import ActivationContractABI from "@/abi/ActivationContract.json";
import MarketplaceABI from "@/abi/Marketplace.json";
import GamePassABI from "@/abi/GamePass.json";

interface ContractConfig {
  abi: unknown[];
  address: string;
}

/**
 * Returns the ABI and deployed address for a given contract.
 * Throws if the address is not configured (contract not deployed yet).
 */
export function getContractConfig(name: ContractName): ContractConfig {
  const addressMap: Record<ContractName, string | undefined> = {
    KeyCoin: process.env.NEXT_PUBLIC_KEYCOIN_ADDRESS,
    GameToken: process.env.NEXT_PUBLIC_GAMETOKEN_ADDRESS,
    GameStore: process.env.NEXT_PUBLIC_GAMESTORE_ADDRESS,
    ActivationContract: process.env.NEXT_PUBLIC_ACTIVATION_ADDRESS,
    Marketplace: process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS,
    GamePass: process.env.NEXT_PUBLIC_GAMEPASS_ADDRESS,
  };

  const address = addressMap[name];
  if (!address) {
    throw new Error(
      `[contracts] ${name} address not configured. ` +
        `Set NEXT_PUBLIC_${name.toUpperCase()}_ADDRESS in .env.local after deploying.`
    );
  }

  const abiMap: Record<ContractName, unknown[]> = {
    KeyCoin: KeyCoinABI,
    GameToken: GameTokenABI,
    GameStore: GameStoreABI,
    ActivationContract: ActivationContractABI,
    Marketplace: MarketplaceABI,
    GamePass: GamePassABI,
  };

  return { abi: abiMap[name], address };
}
